#! /usr/bin/env python

import rospy
import tf2_ros
from geometry_msgs.msg import TransformStamped
from gazebo_msgs.srv import GetModelState, GetModelStateRequest

tf_broadcaster = tf2_ros.TransformBroadcaster()
rospy.wait_for_service ('/gazebo/get_model_state')
get_model_srv = rospy.ServiceProxy('/gazebo/get_model_state', GetModelState)


model = GetModelStateRequest()
model.model_name='march'
rate = rospy.Rate(10)

while not rospy.is_shutdown():
    rospy.sleep(rate)

    result = get_model_srv(model)

    transform = TransformStamped()
    transform.header.stamp = rospy.Time.now()
    transform.header.frame_id = 'world'
    transform.child_frame_id = 'base_link'
    transform.transform.translation = result.pose.position
    transform.transform.rotation = result.pose.orientation

    tf_broadcaster.sendTransform(transform)
