#! /usr/bin/env python
import rospy
import tf2_ros
from geometry_msgs.msg import TransformStamped
from gazebo_msgs.srv import GetModelState, GetModelStateRequest

rospy.init_node('to_world_transform', anonymous=True)
rospy.loginfo("Exoskeleton is mobile")

transform = TransformStamped()
transform.header.frame_id = 'world'
transform.child_frame_id = 'base_link'
tf_broadcaster = tf2_ros.TransformBroadcaster()

rospy.wait_for_service('/gazebo/get_model_state')
get_model_srv = rospy.ServiceProxy('/gazebo/get_model_state', GetModelState)
model = GetModelStateRequest()
model.model_name = 'march'

rate = rospy.Rate(10)

while not rospy.is_shutdown():
    try:
        result = get_model_srv(model)
        transform.header.stamp = rospy.Time.now()
        transform.transform.translation = result.pose.position
        transform.transform.rotation = result.pose.orientation

        tf_broadcaster.sendTransform(transform)
    except rospy.ServiceException as e:
        rospy.loginfo("Get Model State service call failed:  {0}".format(e))
    rate.sleep()
